import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import { StateProvider } from "@/components/StateProvider";
// import { GoogleOAuthProvider } from "@react-oauth/google";
// const googleClientId = process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID || "";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "NEXT Start",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        {/* <GoogleOAuthProvider clientId={googleClientId}> */}
        <StateProvider>
          <Navbar />
          <main className=" py-[100px] px-2 lg:px-4 mx-auto">
            <div className=" px-2 md:p-0">{children}</div>
          </main>
        </StateProvider>
        {/* </GoogleOAuthProvider> */}
      </body>
    </html>
  );
}
